### ISSUE TITLE
Tagとはなんぞ

### ISSUE THREAD

**Issue by Takechan-0** [CreideaNITNC/Tuthub-Specification#4]
[SwiftUI Tutrials](https://developer.apple.com/tutorials/swiftui)は

- 差分＆解説
- Section
- ページ
- Chapter
- （チュートリアル全体）

っていう階層構造になってて，TutHub通信プロトコルのCommitが差分＆解説に，Dataがチュートリアル全体にあたることは分かってるんやけど，Tagはページにあたるものって認識でOK？（もしそうなら「Tag」っていう命名もどうかと思ってしまう）
あと，その場合Section・ChapterにあたるものはTutHubに無いことになるけどそれで良いん？

**Comment by lemo-nade-room** [comment]
tagはページ認識でOK
